#!/bin/bash
# TODO(Kyle) Change this directory to the actual binary path for the RoboRIO

rio_addr="roboRIO-1678-FRC.local"
if [ $# -gt 0 ]
then
        rio_addr=$1
fi

sshpass -p '' ssh admin@$rio_addr <<'ENDSSH'
kill -9 $(pidof FRCUserProgram)
ENDSSH
sleep 0.5
sshpass -p '' scp bazel-bin/frc1678/frc1678 admin@$rio_addr:/home/lvuser/FRCUserProgram
sshpass -p '' scp frc1678/auto/*.auto admin@$rio_addr:/home/lvuser
sshpass -p '' scp robotCommand admin@$rio_addr:/home/lvuser/robotCommand
sshpass -p '' ssh admin@$rio_addr <<'ENDSSH'
/usr/local/frc/bin/frcKillRobot.sh -t -r;
ENDSSH
