cc_library(
  name = "gyro",
  srcs = ["gyro_interface.cpp", "gyro_reader.cpp"],
  hdrs = ["gyro_interface.h", "gyro_reader.h"],
  visibility = ["//visibility:public"],
  deps = ["//muan", "@wpilib//:main", "//unitscpp"]
)
