cc_library (
  name = "vision",
  srcs = glob(["**/*.cpp"]),
  hdrs = glob(["**/*.h"]),
  deps = ["@wpilib//:main", "//frc1678:robot_subsystems", "//muan", "//muan/unitscpp"],
  visibility = ["//visibility:public"]
)

