cc_library(
  name = "pivot_controller",
  srcs = ["pivot_controller.cpp"],
  hdrs = ["pivot_controller.h"],
  deps = ["//muan", "//muan/unitscpp", "//robot_constants"],
  visibility = ["//visibility:public"]
)
