cc_library(
  name = 'auto-test',
  srcs = glob(["**/*.cpp"]),
  deps = ["@wpilib//:main", "//drivetrain/drivetrain:drivetrain_lib", "//unitscpp"],
  hdrs = glob(["**/*.h"]),
  visibility=["//visibility:public"]
)
