package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'citrus_button',
  hdrs = ['citrus_button.h'],
  srcs = ['citrus_button.cpp'],
  deps = ['//third_party/wpilibsuite:wpilib']
)

cc_library(
  name = 'smart_dashboard_helper',
  hdrs = ['smart_dashboard_helper.h'],
  srcs = ['smart_dashboard_helper.cpp'],
  deps = ['//muan:logging', '//third_party/wpilibsuite:wpilib']
)
