cc_library(
  name = "arm_subsystem",
  srcs = ["arm_subsystem.cpp"],
  hdrs = ["arm_subsystem.h"],
  deps = ["//muan", "@wpilib//:main", "//arm/pivot:pivot_controller", "//arm/elevator:elevator_controller", "//frc1678:robot_ports", "//muan:utils"],
  visibility = ["//visibility:public"]
)
