cc_library(
  name = "arm_subsystem",
  srcs = ["arm_subsystem.cpp"],
  hdrs = ["arm_subsystem.h"],
  deps = [
    "//muan",
    "//third_party/wpilibsuite:wpilib",
    "//arm/pivot:pivot_controller",
    "//arm/shooter:shooter_controller",
    "//arm/elevator:elevator_controller",
    "//frc1678:robot_ports",
    "//muan:utils",
    "//muan/unitscpp",
    "//robot_constants",
    "//utils:smart_dashboard_helper"
  ],
  visibility = ["//visibility:public"]
)
