cc_library(
  name = "shooter_controller",
  srcs = ["shooter_bang.cpp"],
  hdrs = ["shooter_bang.h"],
  deps = ["//muan", "//muan:utils", "//muan/unitscpp"],
  visibility = ["//visibility:public"]
)
