cc_library(
  name = "main",
  srcs = ["vision.cpp"],
  hdrs = ["vision.h"],
  deps = ["//frc1678:robot_subsystems", "//muan", "//muan/unitscpp", "//citrus_socket"],
  visibility = ["//visibility:public"]
)
